ALTER TABLE ORDERS ADD COLUMN QUANTITY INT;

-- Populate the QUANTITY column for demonstration
UPDATE ORDERS SET QUANTITY = 15 WHERE ORD_NO = 50;
UPDATE ORDERS SET QUANTITY = 5 WHERE ORD_NO = 51;
UPDATE ORDERS SET QUANTITY = 12 WHERE ORD_NO = 52;
UPDATE ORDERS SET QUANTITY = 20 WHERE ORD_NO = 53;
UPDATE ORDERS SET QUANTITY = 8 WHERE ORD_NO = 54;

-- Calculate the total sales for each salesman where quantity sold is greater than 10
SELECT s.NAME AS Salesman_Name, 
       SUM(o.PURCHASE_AMT) AS Total_Sales
FROM ORDERS o
JOIN SALESMAN s ON o.SALESMAN_ID = s.SALESMAN_ID
WHERE o.QUANTITY > 10
GROUP BY s.NAME;
