-- Display the SALESMAN table ordered by COMMISSION in ascending order
SELECT *, CAST(SUBSTRING(COMMISSION, 1, LENGTH(COMMISSION) - 1) AS UNSIGNED) AS COMMISSION_NUM
FROM SALESMAN
ORDER BY COMMISSION_NUM ASC;